### ISSUE TITLE
Hardcoded redis address!

### ISSUE THREAD

**Issue by rdek** [Fuzzapi/fuzzapi#68]
https://github.com/Fuzzapi/fuzzapi/blob/master/config/initializers/sidekiq.rb

Guys - for real?

`redis_url = ENV['REDIS_URL'] || "redis://redis:6379/0"`

**Comment by kowalskey** [comment]
:+1: docs should mention that you have to add entry to DNS or use localhost as default.
Also related error: https://github.com/Fuzzapi/fuzzapi/issues/50

**Comment by lalithr95** [comment]
@rdek its not a secret, you can set the env variable or simple export it for your shell. Default redis address is for docker support, so I don't see any issue with that config.

Feel free to reopen if you disagree.

**Comment by Dineshboss** [comment]
so how to solve this issue as I have also got stuck with the same issue. I need to make any change to sidekiq.rb file?
I am using Fuzzapi on Kali Linux and Redis server is running on 127.0.0.1:6379


The following URL 
redis_url = ENV['REDIS_URL'] || "redis://redis:6379/0"   is the standard URL which is set in the file what I need to change in this URL so that I can resolve my error.
plz, help me out as it is so frustrating..
